version: '3.7'
services:
  db:
    container_name: mysql
    image: 'mysql:5.7'
    ports:
      - 3308:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./docker-config/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - ./docker-config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=segredo
    command: --init-file /docker-entrypoint-initdb.d/init.sql
